Fix omitting of optional record fields
aeternity/aepp-calldata-js pull request #147
Opened 2022-07-05 22:07 UTC by davidyuk

2022-07-11 13:32 UTC, dincho requested changes
Please move the implementation to the InternalMapper only. The internal structures should not be affected by this changes.

Also, please add release notes.

2022-07-11 13:46 UTC, dincho commented on tests/integration/encoder.sh
> +test_encoder 'test_option_record({x = 42, y = None})'
Does the CLI compiler works without providing the optional ?

2022-07-12 10:16 UTC, davidyuk commented on CHANGELOG.md
> +- Fix omitting of optional record fields
Not sure about this, omitting of optional fields was broken after the previous release (at the same time as `Set` support)

2022-07-12 14:06 UTC, merged

2022-07-13 14:14 UTC, davidyuk commented on CHANGELOG.md
> +- Fix omitting of optional record fields
Yep, I found it while running sdk tests with the calldata from master branch