Accept only ae-encoded addresses, check its length
aeternity/aepp-calldata-js pull request #82
Opened 2021-11-02 10:48 UTC by davidyuk

I'm proposing to
- ensure that address length is correct to faster find errors
- accept only ae-encoded addresses to simplify interface and validation (still able to create addresses internally as byte arrays (to avoid extra encoding/decoding) by passing `raw` flag)

2021-11-02 12:58 UTC, dincho requested changes
I disagree with the proposed implementation as switching logic based on boolean arguments is considered bad practice in general.

Length validation is OK, and I would accept it

2021-11-02 12:58 UTC, dincho commented on src/types/FateBytes.js
>      // not implemented yet
could you please also remove this comment as it's now implemented

2021-11-08 12:16 UTC, davidyuk commented on src/Serializer.js
> +        const typeName = data.typeName || data.constructor.name.slice(4)
having two classes with the same class name is a tricky thing, proposing this as a workaround

2021-11-08 12:16 UTC, davidyuk commented on src/types/FateAddresses.js
> +].reduce((prev, [name, ...args]) => {
Combining these types into a single file to simplify the making of changes, not sure is it acceptable. But I don't think these types got a custom behavior in a foreseen future.

2021-11-11 16:54 UTC, dincho requested changes
too much meta

2021-11-20 18:35 UTC, dincho commented
@davidyuk would you benefit from changes in #89 as you mentioned there ?

2021-11-22 10:36 UTC, dincho commented
sorry for the jaded review, thanks for your time

2021-11-22 10:37 UTC, dincho approved these changes

2021-11-22 10:37 UTC, merged

2021-11-22 10:47 UTC, davidyuk commented
it is fine, was interesting to know your opinion about the above stuff