Accept object as map
aeternity/aepp-calldata-js pull request #90
Opened 2021-11-18 21:03 UTC by davidyuk

SDK was accepting objects as maps before calldata, it looks useful to me, so I'm proposing to support this.
https://github.com/aeternity/aepp-sdk-js/blob/bc65bd78ecd6f8876c0642b11c6ba0aa1f5e4598/docs/guides/contracts.md#sophia-datatype-cheatsheet

2021-11-19 13:09 UTC, dincho commented
Wait a second, so you're arguing around in the PRs and issues how you don't like and don't want other types (i.e. Variant) to accept multiple value structures and you're proposing yourself the very same concept here ?

I don't get it, I think you're very biased with the legacy in the SDK and that's not a benefit for this library. It won't hold the legacy mistakes of the SDK sorry.

However, the main reason this won't be accepted is that POJO's don't allow other objects as keys while JS `Map` and Sophia maps does.

2021-11-22 14:57 UTC, davidyuk commented
> the main reason this won't be accepted is that POJO's don't allow other objects as keys while JS Map and Sophia maps does

Calldata accepts Numbers currently, but they also can't represent such big numbers that Sophia supports.

> I don't get it, I think you're very biased with the legacy in the SDK and that's not a benefit for this library. It won't hold the legacy mistakes of the SDK sorry.

I don't think this was a legacy mistake. JS Objects are good in representing `map(string/int, *)`. Historically they are more popular and can be easier for someone to use. @marc0olo @nikita-fuchs what do you think?

> Wait a second, so you're arguing around in the PRs and issues how you don't like and don't want other types (i.e. Variant) to accept multiple value structures and you're proposing yourself the very same concept here ?

Thread this as a third-party contribution 😄 I'm not 100% sure about stuff that I'm proposing. Comparing it with similar issues:

https://github.com/aeternity/aepp-calldata-js/pull/76
I'm taking this one back (see the end of discussion), the runtime checks don't need to be so strict, the well-know JS behaviour (conversion of everything to bool) (+ TS validation in future) is acceptable.

https://github.com/aeternity/aepp-calldata-js/pull/82
I don't know any strict agreement on how `bytes`, `hash`, `signature` types should be represented, but in most of the cases we have aeternity addresses as base58 encoded strings with a prefix. To enforce this should be clearer for developers than to list base58 strings alongside with all available formats inherited from "low-level" types.

https://github.com/aeternity/aepp-calldata-js/pull/81#discussion_r742716430
Here we would made different ways by creation a new entity (a helper function) without strong reasinong (like having a class for Variants). The support of existing JS entities (if they aplicable and makes sense) seems not so bad than creating an extra ones.

2021-11-22 15:08 UTC, dincho commented
> Thread this as a third-party contribution

I usually wouldn't reason that much with "external" contributors. If you keep trying to change all the representations and internals of this lib for non-sense reason I might change my mind for other compromises as well.

As I said 1000s times already this is **STANDALONE LIBRARY** it has nothing to do with end users and you're free to implement any convenient hypster types and representations in the SDK.

I 100% disagree with this ticket, thus I've closed it, keeping open won't change my mind.

2021-11-22 15:09 UTC, dincho requested changes
https://github.com/aeternity/aepp-calldata-js/pull/90#issuecomment-975623013

2021-11-22 16:33 UTC, dincho commented
> Calldata accepts Numbers currently,

I don't mind forbidding that :)

2021-11-24 09:24 UTC, dincho commented
Missing docs update BTW

2021-11-24 13:34 UTC, thepiwo approved these changes

2021-12-03 16:47 UTC, dincho commented
after changes in #110 I could reconsider this if it can be added with changes only in `CanonicalMapper`

2021-12-12 14:53 UTC, dincho commented
@davidyuk care to update this or close it ?

2021-12-17 11:15 UTC, dincho submitted a review, later dismissed

2021-12-17 11:16 UTC, dincho commented
Could you please also update the docs ?

2021-12-27 15:06 UTC, dincho approved these changes

2021-12-27 15:06 UTC, merged